config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "texts#index"
  resources :texts
  resources :movies
  devise_for :users
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :genre, :title, :url, presence: true
end

app/models/text.rb
class Text < ApplicationRecord
  validates :genre, :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    if params[:genre] == nil
      @texts = Text.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"])
    else
      @texts = Text.where(genre: params[:genre])
    end
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def max_width
    "mw-xl"
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      options = {
        hard_wrap: true,
      }
      extensions = {
        no_intra_emphasis: true,
        tables: true,
        fenced_code_blocks: true,
        autolink: true,
        quote: true,
      }
      renderer = Redcarpet::Render::HTML.new(options)
      @markdown = Redcarpet::Markdown.new(renderer, extensions)
    end
    @markdown.render(text).html_safe
  end
end

app/helpers/texts_helper.rb
module TextsHelper
  def page_title
    if params[:genre] == nil
      "Ruby/Rails"
    else
      params[:genre]
    end
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar  navbar-dark ">
<div class="mx-auto">
  <%= link_to "ブログ", "https://utina.yoshitokamizato.com/", class: "navbar-brand", target: :_blank , rel: "noopener noreferrer" %>
  <%= link_to "Youtube", "https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag", class: "navbar-brand", target: :_blank, rel: "noopener noreferrer"  %>
</div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark mw-lg mx-auto">
  <%= link_to "やんばるCODE", texts_path, class: "navbar-brand" %>
  <button class="navbar-toggler active" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Rails
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Ruby/Rails教材", texts_path, class: "dropdown-item" %>
          <%# <a class="dropdown-item" href="/">Ruby/Rails教材</a> %>
          <a class="dropdown-item" href="/movies">動画教材</a>
          <%= link_to "AWS講座", texts_path(genre: "AWS"), class: "dropdown-item" %>
          <a class="dropdown-item" href="#">プログラミング勉強会</a>
          <a class="dropdown-item" href="#">質問集</a>
          <%= link_to "チャレンジ問題集", texts_path(genre: ""), class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          PHP
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "PHPテキスト教材", texts_path(genre: "Php"), class: "dropdown-item" %>
          <%# <a class="dropdown-item" href="#">PHPテキスト教材</a> %>
          <a class="dropdown-item" href="#">PHP動画教材</a>
        </div>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          フロント
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/">HTML&CSS</a>
          <a class="dropdown-item" href="#">JavaScript</a>
          <a class="dropdown-item" href="#">TypeScript</a>
          <a class="dropdown-item" href="#">Angular</a>
          <a class="dropdown-item" href="#">Vue</a>
        </div>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">対談</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">マネタイズ</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">LINE</a>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          マイページ 
        </a>
        <div class="dropdown-menu active" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">進捗管理</a>
          <%= link_to "アカウント編集", edit_user_registration_path, class:"dropdown-item" %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>チーム開発 やんばるCODE教材クローン</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="fixed-top base-bg-color">
      <%= render 'layouts/header' %>
    </header>
    <%= render 'layouts/flash' %>
    <main>
      <%# max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer class="fixed-bottom base-bg-color">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-12 col-md-6 col-lg-4 text-card-container">
        <div class="card">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg>
          <div class="card-body">
            <p class="card-text"><%= movie.title %></p>
            <p class="card-text"><%= movie.genre %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/index.html.erb
<div class="text-title">
  <h3><%= page_title %>テキスト教材</h3>
</div>
<form class="mb-3 mx-auto search-form">
  <div class="form-group">
    <label class="sr-only" for="text-search">教材を探す</label>
    <div class="input-group">
      <i class="fa fa-search search-icon" aria-hidden="true"></i>
      <input type="text-search" class="form-control text-search" id="text-search" placeholder="教材を探す">
    </div>
  </div>
</form>
<div class="container">
  <div class="row">
    <% @texts.each do |text| %>
      <div class="col-12 col-md-6 col-lg-4 text-card-container" id="card-body">
        <%= link_to text, class: "card" do %>
          <svg class="bd-placeholder-img card-img-top" width="100%" height="200" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg>
          <div class="card-body">
            <p class="card-text"><%= text.title %></p>
            <p class="card-text"><%= text.genre %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/show.html.erb
<h2><%= @text.title %></h2>
<%= markdown(@text.content) %>